NeuroShare To HDF5 (NS2HDF): CHdf_export Class Reference
CHdf_export Class Reference
#include <Hdf_export.h>
Public Member Functions
CHdf_export ()
~CHdf_export (void)
void closeFile (void)
Closes the hdf5 file.
int createFile (CString sourceFile, CString hdfFile)
Creates a hdf5 file with the specified name.
int write_fileInfo (ns_FILEINFO *fi)
Creates a data set containing file info.
herr_t create_root_groups (entityType t)
Creates the hdf5 basic groups: unknown, event, neural, segment, analog.
int write_analog (double *d, UINT n, DWORD index, ns_ANALOGINFO ai)
Writes analog data in hdf5 format.
int write_event_word (eventWord *data, UINT n, DWORD index, ns_EVENTINFO ai)
Writes word sized event data in hdf5 format.
int write_event_byte (eventByte *data, UINT n, DWORD index, ns_EVENTINFO ai)
Writes byte sized event data in hdf5 format.
int write_event_dword (eventDword *data, UINT n, DWORD index, ns_EVENTINFO ai)
Writes double word sized event data in hdf5 format.
int write_event_text (BYTE *data, UINT n, DWORD index, ns_EVENTINFO ai)
Writes text or csv event data in hdf5 format.
int create_single_segment_group (DWORD index, ns_SEGMENTINFO info, ns_SEGSOURCEINFO *info_source)
Creates a group for segment data.
int write_segment_item (double t, double *data, DWORD index, UINT item, UINT sourceCount, UINT maxSampleCount)
Writes one single segment data in hdf5 format.
int write_neural (double *data, ns_NEURALINFO info, UINT size, UINT index)
Writes neural data in hdf5 format.
Private Member Functions
hid_t get_string_type (UINT len)
function result and error output
herr_t write_single_attribute (hid_t hSet, char szName[], int hdfType, void *data)
writes one single attribute variable to a dataset
int write_event (void *data, char name[], hid_t hDataType, UINT n, ns_EVENTINFO ai)
Writes event data and the event attribute into the hdf5 file.
hid_t write_event_info (hid_t dataset_id, ns_EVENTINFO eventInfo)
Writes the event attributes.
herr_t write_neural_info (hid_t h, ns_NEURALINFO info)
Writes the neural attributes.
herr_t write_segment_info (hid_t h, ns_SEGMENTINFO info)
Writes the segment attributes.
herr_t write_segment_sourceInfo (hid_t h, char name[], ns_SEGSOURCEINFO *info, UINT number_of_sources)
Writes the sources (channels) attributes used in segment entities.
herr_t write_analog_info (hid_t hSet, ns_ANALOGINFO info)
Writes the analog attributes.
Private Attributes
CString path_source
path to source file and to the targeted hdf5 file
CString path_hdf
hid_t file_id
herr_t hOK
hdf5 file handle
Detailed Description
This class handles write operations on the hdf5 file. It creates and closes the hdf5 file, writes data and attributes into it.
Definition at line 75 of file Hdf_export.h.
Constructor & Destructor Documentation
CHdf_export::CHdf_export ()
Definition at line 49 of file Hdf_export.cpp.
CHdf_export::~CHdf_export (void)
Definition at line 53 of file Hdf_export.cpp.
Member Function Documentation
void CHdf_export::closeFile (void)
Closes the hdf5 file.
Definition at line 56 of file Hdf_export.cpp.
Referenced by _tmain().
herr_t CHdf_export::create_root_groups (entityType t)
Creates the hdf5 basic groups: unknown, event, neural, segment, analog.
Creates HDF5 groups for the 5 basic entity types: analog, segment, event, neural, unknown data.
parameters:
t as entityType: the entity type for which you want to create the group returns:
herr_t
Definition at line 83 of file Hdf_export.cpp.
Referenced by ShowEntityInfo().
int CHdf_export::create_single_segment_group (DWORD index, ns_SEGMENTINFO info, ns_SEGSOURCEINFO * info_source)
Creates a group for segment data.
Creates a group for one single segment entity.
This segment entity will contain distinct groups for each data item and for each source info. Each data item contains on his part two data sets: one for the time stamp and one for the multi-channel data
parameters:
index as DWORD: global index of the current analog entity
info as ns_SEGMENTINFO: neuroshare segment info
info_source as ns_SEGSOURCEINFO: neuroshare segment source info
Definition at line 347 of file Hdf_export.cpp.
Referenced by getSegment().
int CHdf_export::createFile (CString sourceFile, CString hdfFile)
Creates a hdf5 file with the specified name.
Creates a HDF5 file with the specified path. This function also saves the pathes to the source and target data files into the appropriate private variables.
parameters:
sourceFile: full path tot the source data file
hdfFile: full path to the target HDF5 file
Definition at line 67 of file Hdf_export.cpp.
Referenced by _tmain().
hid_t CHdf_export::get_string_type (UINT len) [private]
function result and error output
creates a string data type with specified length
Returns a hdf5 string type
parameters:
len as UINT: length of the string in bytes return:
string type as hid_t
Definition at line 290 of file Hdf_export.cpp.
Referenced by write_event_text().
int CHdf_export::write_analog (double * d, UINT n, DWORD index, ns_ANALOGINFO ai)
Writes analog data in hdf5 format.
This function writes one analog entity into the hdf5 file.
parameters:
d as double*: pointer to analog data
n as UINT: total number of values, needed to set the correct size of the dataset
index as DWORD: global index of the current analog entity
ai as ns_ANALOGINFO: neuroshare analog info
Definition at line 159 of file Hdf_export.cpp.
Referenced by ShowAnalog().
herr_t CHdf_export::write_analog_info (hid_t h, ns_ANALOGINFO info) [private]
Writes the analog attributes.
Writes the neuroshare analog info and anchors it to the specified handle.
parameters:
h: handle of the element to tag
info: neuroshare analog info
Definition at line 539 of file Hdf_export.cpp.
Referenced by write_analog().
int CHdf_export::write_event (void * data, char name[], hid_t hDataType, UINT n, ns_EVENTINFO ai) [private]
Writes event data and the event attribute into the hdf5 file.
Writes event data and the event attribute into the hdf5 file The data type has to be specified, if it is a hdf5 compound type, you have to build it first and pass the hdf5 compound type handle to this function.
parameters:
data: pointer to your data structures. It is a (void*) as we use different datatypes
name: element name
hDataType: handle of the hdf5 data type
n: number of items
ai: neuroshare event info for the attribute
Definition at line 193 of file Hdf_export.cpp.
Referenced by write_event_byte(), write_event_dword(), and write_event_word().
int CHdf_export::write_event_byte (eventByte * data, UINT n, DWORD index, ns_EVENTINFO ai)
Writes byte sized event data in hdf5 format.
Writes one event entity which contains byte sized data.
parameters:
data: pointer to the data
n as UINT: total number of values, needed to set the correct size of the dataset
index as DWORD: global index of the current analog entity
ai as ns_EVENTINFO: neuroshare analog info
Definition at line 224 of file Hdf_export.cpp.
Referenced by getEvent_byte().
int CHdf_export::write_event_dword (eventDword * data, UINT n, DWORD index, ns_EVENTINFO ai)
Writes double word sized event data in hdf5 format.
Writes one event entity which contains double word sized data.
parameters:
data: pointer to the data
n as UINT: total number of values, needed to set the correct size of the dataset
index as DWORD: global index of the current analog entity
ai as ns_EVENTINFO: neuroshare analog info
Definition at line 246 of file Hdf_export.cpp.
Referenced by getEvent_dword().
herr_t CHdf_export::write_event_info (hid_t h, ns_EVENTINFO info) [private]
Writes the event attributes.
Writes the neuroshare event info and anchors it to the specified handle.
parameters:
h: handle of the element to tag
info: neuroshare event info
Definition at line 403 of file Hdf_export.cpp.
Referenced by write_event(), and write_event_text().
int CHdf_export::write_event_text (BYTE * data, UINT n, DWORD index, ns_EVENTINFO ai)
Writes text or csv event data in hdf5 format.
Writes one event entity which contains text or csv items.
parameters:
data as BYTE*: pointer to data array
n as UINT: total number of values, needed to set the correct size of the dataset
index as DWORD: global index of the current analog entity
ai as ns_EVENTINFO: neuroshare analog info
Definition at line 305 of file Hdf_export.cpp.
Referenced by getEvent_text().
int CHdf_export::write_event_word (eventWord * data, UINT n, DWORD index, ns_EVENTINFO ai)
Writes word sized event data in hdf5 format.
Writes one event entity which contains word sized data.
parameters:
data: pointer to the data
n as UINT: total number of values, needed to set the correct size of the dataset
index as DWORD: global index of the current analog entity
ai as ns_EVENTINFO: neuroshare analog info
Definition at line 269 of file Hdf_export.cpp.
Referenced by getEvent_word().
int CHdf_export::write_fileInfo (ns_FILEINFO * fi)
Creates a data set containing file info.
Creates a data set containing the file info as specified in the neuroshare file.
parameters:
fi as ns_FILEINFO*: neuroshare file info return:
int: Returns a non-negative value if successful; otherwise returns a negative value.
Definition at line 115 of file Hdf_export.cpp.
Referenced by main_processFile().
int CHdf_export::write_neural (double * data, ns_NEURALINFO info, UINT size, UINT index)
Writes neural data in hdf5 format.
This function writes one analog entity into the hdf5 file.
parameters:
data: pointer to analog data
info: neuroshare neural info
size: data size counted in elements (not bytes)
index: current item index
Definition at line 575 of file Hdf_export.cpp.
Referenced by getNeural().
herr_t CHdf_export::write_neural_info (hid_t h, ns_NEURALINFO info) [private]
Writes the neural attributes.
Writes the neuroshare neural info and anchors it to the specified handle.
parameters:
h: handle of the element to tag
info: neuroshare neural info
Definition at line 488 of file Hdf_export.cpp.
Referenced by write_neural().
herr_t CHdf_export::write_segment_info (hid_t h, ns_SEGMENTINFO info) [private]
Writes the segment attributes.
Writes the neuroshare segment info and anchors it to the specified handle.
parameters:
h: handle of the element to tag
info: neuroshare segment info
Definition at line 424 of file Hdf_export.cpp.
Referenced by create_single_segment_group().
int CHdf_export::write_segment_item (double t, double * data, DWORD index, UINT item, UINT sourceCount, UINT maxSampleCount)
Writes one single segment data in hdf5 format.
Creates one single segment data item. Each data item contains on his part two data sets: one for the time stamp and one for the multi-channel data
parameters:
t as double: time stamp
data as double*: pointer to data
index as DWORD: global index of the current analog entity
item as UINT: current item number
Definition at line 368 of file Hdf_export.cpp.
Referenced by getSegment().
herr_t CHdf_export::write_segment_sourceInfo (hid_t h, char name[], ns_SEGSOURCEINFO * info, UINT number_of_sources) [private]
Writes the sources (channels) attributes used in segment entities.
Creates a data set containing the neuroshare segment source info.
parameters:
h: handle of the element to tag
name[]: name of the tag
info: opinter to the segment source info
Definition at line 446 of file Hdf_export.cpp.
Referenced by create_single_segment_group().
herr_t CHdf_export::write_single_attribute (hid_t h, char szName[], int hdfType, void * data) [private]
writes one single attribute variable to a dataset
Creates an attribute and anchors it to the specified element
parameters:
h: handle where to anchor the tag
szName[]: name of the tag
hdfType: data type in hdf5 notation
data: pointer to the data
Definition at line 510 of file Hdf_export.cpp.
Referenced by write_analog_info(), write_event_info(), write_neural_info(), and write_segment_info().
Member Data Documentation
hid_t CHdf_export::file_id [private]
Definition at line 125 of file Hdf_export.h.
Referenced by closeFile(), create_root_groups(), create_single_segment_group(), createFile(), write_analog(), write_event(), write_event_text(), write_fileInfo(), write_neural(), write_segment_item(), and write_segment_sourceInfo().
herr_t CHdf_export::hOK [private]
hdf5 file handle
Definition at line 126 of file Hdf_export.h.
Referenced by createFile(), write_analog(), write_event(), write_event_byte(), write_event_dword(), write_event_text(), write_event_word(), write_fileInfo(), write_neural(), write_segment_item(), and write_segment_sourceInfo().
CString CHdf_export::path_hdf [private]
Definition at line 123 of file Hdf_export.h.
Referenced by createFile().
CString CHdf_export::path_source [private]
path to source file and to the targeted hdf5 file
Definition at line 123 of file Hdf_export.h.
Referenced by createFile().
The documentation for this class was generated from the following files:
ns2hdf/Hdf_export.h
ns2hdf/Hdf_export.cpp