NeuroShare To HDF5 (NS2HDF): ns2hdf/ns2hdf.cpp File Reference
ns2hdf/ns2hdf.cpp File Reference
#include <atlbase.h>
#include <algorithm>
#include <stdio.h>
#include <conio.h>
#include <atlstr.h>
#include <windows.h>
#include <vector>
#include <iterator>
#include <NsLibraryImpMgr.h>
#include <ns_common.h>
#include <NsFile.h>
#include "Hdf_export.h"
Functions
void checkNullTermination (char c[], int l)
CString GetAppPathName ()
CString GetAppPath ()
void PressAKeyToContinue ()
ns_FILEINFO readFileInfo (NsFile const &rcLib)
void ShowFileInfo (ns_FILEINFO fileInfo)
void ShowEntityInfo (NsFile const &rcLib)
void getEvent_text (NsFile const &rcLib, DWORD idEntity, ns_ENTITYINFO isEntityInfo, ns_EVENTINFO isEventInfo)
void getEvent_word (NsFile const &rcLib, DWORD idEntity, ns_ENTITYINFO isEntityInfo, ns_EVENTINFO isEventInfo)
void getEvent_byte (NsFile const &rcLib, DWORD idEntity, ns_ENTITYINFO isEntityInfo, ns_EVENTINFO isEventInfo)
void getEvent_dword (NsFile const &rcLib, DWORD idEntity, ns_ENTITYINFO isEntityInfo, ns_EVENTINFO isEventInfo)
void ShowEvent (NsFile const &rcLib)
void ShowAnalog (NsFile const &rcLib)
void getSegment (NsFile const &rcLib, DWORD idEntity, ns_ENTITYINFO isEntityInfo, ns_SEGMENTINFO isSegmentInfo)
void ShowSegment (NsFile const &rcLib)
void getNeural (NsFile const &rcLib, DWORD idEntity, ns_ENTITYINFO isEntityInfo, ns_NEURALINFO isNeuralInfo)
void ShowRaster (NsFile const &rcLib)
int main_processFile (CString path, CString file)
void main_displayHelp ()
Displays usage information, copyright and contact data.
int _tmain (int argc, _TCHAR *argv[])
Variables
CHdf_export hdf_export
ns_FILEINFO fileInfo
Function Documentation
int _tmain (int argc, _TCHAR * argv[])
Definition at line 811 of file ns2hdf.cpp.
void checkNullTermination (char c[], int l)
Definition at line 123 of file ns2hdf.cpp.
Referenced by readFileInfo(), ShowAnalog(), ShowEvent(), ShowRaster(), and ShowSegment().
CString GetAppPath ()
Definition at line 146 of file ns2hdf.cpp.
Referenced by _tmain().
CString GetAppPathName ()
Definition at line 137 of file ns2hdf.cpp.
Referenced by GetAppPath().
void getEvent_byte (NsFile const & rcLib, DWORD idEntity, ns_ENTITYINFO isEntityInfo, ns_EVENTINFO isEventInfo)
Reads BYTE event data from the specified entity.
parameters:
NsFile const & rcLib: NsFile object
idEntity: entity index
isEntityInfo: neuroshare entity info
isEventInfo: neuroshare event info
Definition at line 375 of file ns2hdf.cpp.
Referenced by ShowEvent().
void getEvent_dword (NsFile const & rcLib, DWORD idEntity, ns_ENTITYINFO isEntityInfo, ns_EVENTINFO isEventInfo)
Reads DWORD event data from the specified entity.
parameters:
NsFile const & rcLib: NsFile object
idEntity: entity index
isEntityInfo: neuroshare entity info
isEventInfo: neuroshare event info
Definition at line 411 of file ns2hdf.cpp.
Referenced by ShowEvent().
void getEvent_text (NsFile const & rcLib, DWORD idEntity, ns_ENTITYINFO isEntityInfo, ns_EVENTINFO isEventInfo)
Reads text or csv event data from the specified entity.
parameters:
NsFile const & rcLib: NsFile object
idEntity: entity index
isEntityInfo: neuroshare entity info
isEventInfo: neuroshare event info
Definition at line 297 of file ns2hdf.cpp.
Referenced by ShowEvent().
void getEvent_word (NsFile const & rcLib, DWORD idEntity, ns_ENTITYINFO isEntityInfo, ns_EVENTINFO isEventInfo)
Reads word event data from the specified entity.
parameters:
NsFile const & rcLib: NsFile object
idEntity: entity index
isEntityInfo: neuroshare entity info
isEventInfo: neuroshare event info
Definition at line 339 of file ns2hdf.cpp.
Referenced by ShowEvent().
void getNeural (NsFile const & rcLib, DWORD idEntity, ns_ENTITYINFO isEntityInfo, ns_NEURALINFO isNeuralInfo)
Reads the specified neural entity and passes the information to the hdf_export object which writes it into the HDF5 file.
parameters:
NsFile const & rcLib: NsFile object
idEntity: current entity index
isEntityInfo: neuroshare entity info
isNeuralInfo: neuroshare neural info
Definition at line 686 of file ns2hdf.cpp.
Referenced by ShowRaster().
void getSegment (NsFile const & rcLib, DWORD idEntity, ns_ENTITYINFO isEntityInfo, ns_SEGMENTINFO isSegmentInfo)
Reads the segment data and writes them into the hdf5 file
The segment entity allows to save data from multiple electrodes so first we allocate enough memory for all channel information (i.e. ns_SEGSOURCEINFO)
read the channel info
allocate memory for the data. The data size is number of channels * maxSampleCount Check if the allocation was successful
create a segment group
read all items from the current segment and write them into the previously created segment group
free the reserved memory for the data
done!
Definition at line 565 of file ns2hdf.cpp.
Referenced by ShowSegment().
void main_displayHelp ()
Displays usage information, copyright and contact data.
Definition at line 798 of file ns2hdf.cpp.
Referenced by _tmain().
int main_processFile (CString path, CString file)
Opens the data file, reads data and saves it in the hdf5 format.
The neuroshare library usually recognises the file type and selects automatically the appropriate DLL. But as there seems to be an error with ".mcd" files, we have to constrain the neuroshare library to open this file type with "nsMCDLibrary.dll".
parameters:
path: current path
file: target hdf5 file path
Definition at line 748 of file ns2hdf.cpp.
Referenced by _tmain().
void PressAKeyToContinue ()
Definition at line 154 of file ns2hdf.cpp.
Referenced by _tmain().
ns_FILEINFO readFileInfo (NsFile const & rcLib)
Get file info in neuroshare format
parameters:
NsFile const & rcLib: NsFile object return:
ns_FILEINFO: neuroshare file info
Definition at line 167 of file ns2hdf.cpp.
Referenced by main_processFile().
void ShowAnalog (NsFile const & rcLib)
Processes all analog entities
parameters:
NsFile const & rcLib: NsFile object
Definition at line 501 of file ns2hdf.cpp.
Referenced by main_processFile().
void ShowEntityInfo (NsFile const & rcLib)
Counts the number and type of entities contained in the neuroshare data file. Then it creates hdf5 groups for each existent entity type.
parameters:
NsFile const & rcLib: NsFile object
Definition at line 219 of file ns2hdf.cpp.
Referenced by main_processFile().
void ShowEvent (NsFile const & rcLib)
Processes all event entities
parameters:
NsFile const & rcLib: NsFile object
Definition at line 444 of file ns2hdf.cpp.
Referenced by main_processFile().
void ShowFileInfo (ns_FILEINFO fileInfo)
Shows some info about the selected file
parameters:
fileInfo: neuroshare file info
Definition at line 185 of file ns2hdf.cpp.
Referenced by main_processFile().
void ShowRaster (NsFile const & rcLib)
Processes all neural entities
parameters:
NsFile const & rcLib: NsFile object
Definition at line 706 of file ns2hdf.cpp.
Referenced by main_processFile().
void ShowSegment (NsFile const & rcLib)
Processes all segment entities
parameters:
NsFile const & rcLib: NsFile object
Definition at line 624 of file ns2hdf.cpp.
Referenced by main_processFile().
Variable Documentation
ns_FILEINFO fileInfo
Definition at line 121 of file ns2hdf.cpp.
Referenced by main_processFile(), readFileInfo(), ShowAnalog(), ShowEntityInfo(), ShowEvent(), ShowRaster(), and ShowSegment().
CHdf_export hdf_export
Definition at line 120 of file ns2hdf.cpp.